title: Oleg Balabanov's Homepage
page-top-title: 
top-section-bg-text: RandNLA, ML, Numerical Optimization
home-subtitle: Oleg Balabanov&ensp;
copyright-text: '&copy; Oleg Balabanov 2025-2026. All Rights Reserved.'
